name: marlo
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - certifi=2021.5.30
  - openjdk=8.0.152
  - pip=21.2.2
  - python=3.6.13
  - sqlite=3.45.3
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.37.1
  - wincertstore=0.2
  - zlib=1.2.13
  - pip:
      - async-timeout==4.0.2
      - charset-normalizer==2.0.12
      - cloudpickle==2.2.1
      - crowdai-api==0.1.22
      - dataclasses==0.8
      - future==1.0.0
      - gym==0.19.0
      - gym-notices==0.0.8
      - idna==3.10
      - importlib-metadata==4.8.3
      - jinja2==3.0.3
      - lxml==5.4.0
      - markupsafe==2.0.1
      - marlo==0.0.1.dev23
      - numpy==1.19.5
      - packaging==21.3
      - pyparsing==3.1.4
      - python-gitlab==2.10.1
      - redis==4.3.6
      - requests==2.27.1
      - requests-toolbelt==1.0.0
      - setuptools==44.1.0
      - typing-extensions==4.1.1
      - urllib3==1.26.20
      - zipp==3.6.0

